export enum MODAL_TENANT_ID {
  INPUT_CUSTOMER = "INPUT_CUSTOMER",
  LOAD_DRAFT = "LOAD_DRAFT",
  ALERT_SUCCESS_SAVE_ORDER = "ALERT_SUCCESS_SAVE_ORDER",
  ALERT_SUCCESS_CHECKOUT = "ALERT_SUCCESS_CHECKOUT",
}
